// <auto-generated by="the Blazor I18n Text compiler" />
namespace AditumWebGUI.I18nText.Login
{
    public partial class Login : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Follow Us On"</summary>
        public string FollowUs;

        /// <summary>"Log In"</summary>
        public string LogIn;
    }
}
