// <auto-generated by="the Blazor I18n Text compiler" />
namespace BlazorWebGUI.I18nText.Main
{
    public partial class Main : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About"</summary>
        public string About;

        /// <summary>"Sample Site"</summary>
        public string SiteName;
    }
}
